from pathlib import Path
p=Path('/mnt/data/v53/web/index.html')
s=p.read_text(encoding='utf-8')
css=r'''
<style id="v53-deep-interactive-css">
.v53-launch{margin:12px 8px 0 0!important;box-shadow:0 8px 24px rgba(20,80,50,.14)}
.v53-actionable{cursor:pointer;transition:transform .16s,box-shadow .16s,border-color .16s;position:relative}
.v53-actionable:hover{transform:translateY(-2px);box-shadow:0 10px 28px rgba(0,0,0,.08);border-color:#69a67d!important}
.v53-actionable:after{content:'↗';position:absolute;right:9px;top:7px;font-size:11px;opacity:.35}
.v53-shell{position:fixed;inset:0;background:rgba(4,18,12,.58);backdrop-filter:blur(7px);z-index:100000;display:none;align-items:center;justify-content:center;padding:20px}
.v53-shell.show{display:flex}
.v53-modal{width:min(1180px,96vw);max-height:92vh;overflow:auto;background:#f7faf8;border:1px solid rgba(255,255,255,.45);border-radius:22px;box-shadow:0 30px 90px rgba(0,0,0,.3);padding:18px}
.v53-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;padding:6px 6px 14px}.v53-head h2{margin:.15em 0}.v53-kicker{font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:#39724d;font-weight:800}.v53-close{border:0;border-radius:12px;background:#fff;font-size:22px;width:40px;height:40px;cursor:pointer}
.v53-toolbar{display:flex;flex-wrap:wrap;gap:8px;margin:4px 0 14px}.v53-toolbar button{border:1px solid #cfded4;background:#fff;border-radius:10px;padding:9px 12px;cursor:pointer;font-weight:700}.v53-toolbar button.active{background:#1f6d43;color:#fff;border-color:#1f6d43}
.v53-grid{display:grid;grid-template-columns:1.35fr .85fr;gap:12px}.v53-card{background:#fff;border:1px solid #dfe9e2;border-radius:16px;padding:14px}.v53-card h3{margin:0 0 10px}.v53-pipeline{display:grid;gap:8px}.v53-step{display:flex;gap:10px;align-items:center;padding:10px;border:1px solid #e4ebe6;border-radius:12px}.v53-step i{width:26px;height:26px;border-radius:50%;display:grid;place-items:center;background:#edf4ef;font-style:normal;font-size:12px;font-weight:800}.v53-step.run i{background:#fff3cf}.v53-step.done i{background:#dff2e5}.v53-step.fail i{background:#ffe1e1}.v53-status{margin-left:auto;font-size:11px;color:#708078}.v53-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.v53-kpi{padding:11px;border:1px solid #e2e9e4;border-radius:12px}.v53-kpi small{display:block;color:#738178}.v53-kpi b{font-size:22px}.v53-bars{height:190px;display:flex;align-items:flex-end;gap:7px;padding:10px 4px}.v53-bar{flex:1;border-radius:7px 7px 2px 2px;background:linear-gradient(180deg,#2c7a4b,#9ac4a7);min-height:5px;transition:height .6s}.v53-log{font-family:ui-monospace,SFMono-Regular,monospace;font-size:11px;background:#0d1712;color:#ccebd7;border-radius:12px;padding:10px;max-height:150px;overflow:auto;line-height:1.65}.v53-alert{padding:10px 12px;border-radius:11px;background:#fff8e4;border:1px solid #f1dfaa;margin-top:8px}.v53-good{background:#eaf7ee;border-color:#bfe2c8}.v53-danger{background:#fff0f0;border-color:#efc1c1}.v53-chip{display:inline-block;padding:4px 8px;border-radius:99px;background:#edf4ef;margin:3px;font-size:10px}.v53-tab{display:none}.v53-tab.show{display:block}.v53-map{height:230px;border-radius:14px;background:radial-gradient(circle at 25% 35%,#d7eadc 0 8%,transparent 9%),radial-gradient(circle at 70% 60%,#c7dfce 0 12%,transparent 13%),linear-gradient(135deg,#eef6f0,#dbe9df);position:relative;overflow:hidden;border:1px solid #cadbce}.v53-pin{position:absolute;transform:translate(-50%,-50%);padding:5px 8px;border-radius:99px;background:#1f6d43;color:#fff;font-size:10px;font-weight:800;box-shadow:0 3px 10px rgba(0,0,0,.16)}.v53-table{width:100%;border-collapse:collapse;font-size:12px}.v53-table th,.v53-table td{padding:8px;border-bottom:1px solid #e8eee9;text-align:left}.v53-action-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.v53-action-row button{border:1px solid #cddbd1;background:#fff;border-radius:9px;padding:8px 10px;cursor:pointer}.v53-action-row .primary{background:#1f6d43;color:#fff;border-color:#1f6d43}
@media(max-width:800px){.v53-grid{grid-template-columns:1fr}.v53-kpis{grid-template-columns:1fr 1fr}.v53-modal{padding:12px}}
</style>
'''
marker='</head>'
s=s.replace(marker,css+marker,1)
js=r'''
<script id="v53-deep-interactive-engine">
(function(){
 const SECTIONS=['health','agri','unicef','who','wfp','fao','monitoring'];
 const NAMES={health:'Ministry of Health',agri:'Ministry of Agriculture',unicef:'UNICEF',who:'WHO',wfp:'WFP',fao:'FAO',monitoring:'Projects, Surveys & Nutrition Surveillance'};
 const $=id=>document.getElementById(id);
 const clean=x=>(x?.innerText||x?.textContent||'').replace(/\s+/g,' ').trim();
 let activeSection='fao', activeSubject='Institutional Intelligence', timer=null, seq=0;
 function rootOf(el){const r=el?.closest('.view');return r&&SECTIONS.includes(r.id)?r:null}
 function ctx(sec){
   const r=$(sec); const pick=id=>$(id)?.selectedOptions?.[0]?.textContent||$(id)?.value;
   return {country:pick(sec+'Country')||pick('country')||'Togo',level:pick(sec+'Level')||'National',year:pick(sec+'Year')||'2026'};
 }
 function seed(sec,sub){const c=ctx(sec);let n=0;for(const z of (sec+sub+c.country+c.level+c.year))n=(n*31+z.charCodeAt(0))%997;return n}
 function values(sec,sub){const n=seed(sec,sub);return [0,1,2,3,4,5,6].map(i=>45+((n+i*17)%48));}
 function subject(el,sec){return clean(el?.querySelector('h1,h2,h3,h4,b,strong,th,span'))||clean(el).slice(0,100)||NAMES[sec]}
 function ensure(){
   if($('v53Shell'))return;
   const d=document.createElement('div');d.id='v53Shell';d.className='v53-shell';d.innerHTML=`
   <div class="v53-modal" role="dialog" aria-modal="true">
    <div class="v53-head"><div><div class="v53-kicker">NUTRI.N°1 • Deep Investor Demonstration</div><h2 id="v53Title">Institutional Intelligence</h2><div id="v53Context" class="muted"></div></div><button class="v53-close" onclick="NUTRI53.close()">×</button></div>
    <div class="v53-toolbar"><button data-tab="overview" class="active">⚡ Live Run</button><button data-tab="data">🗄 Data & Provenance</button><button data-tab="gis">🗺 GIS</button><button data-tab="alerts">🚨 Early Warning</button><button data-tab="actions">🎯 Decision Center</button><button data-tab="audit">🔐 Audit Trail</button></div>
    <div id="v53Overview" class="v53-tab show"><div class="v53-grid"><div class="v53-card"><h3>Processing & orchestration</h3><div id="v53Pipeline" class="v53-pipeline"></div><div class="v53-action-row"><button class="primary" onclick="NUTRI53.rerun()">↻ Re-run intelligence</button><button onclick="NUTRI53.drill()">Open drill-down</button><button onclick="NUTRI53.export()">Export executive brief</button></div></div><div class="v53-card"><h3>Live signal profile</h3><div id="v53Bars" class="v53-bars"></div><div id="v53Kpis" class="v53-kpis"></div></div></div><div id="v53Result" class="v53-alert" style="margin-top:12px"></div></div>
    <div id="v53Data" class="v53-tab"><div class="v53-card"><h3>🗄 Data fabric</h3><table class="v53-table" id="v53DataTable"></table><div class="v53-action-row"><button onclick="NUTRI53.sync()">Synchronize sources</button><button onclick="NUTRI53.validate()">Run quality gate</button><button onclick="NUTRI53.provenance()">View provenance chain</button></div></div></div>
    <div id="v53Gis" class="v53-tab"><div class="v53-card"><h3>🗺 Operational GIS simulation</h3><div id="v53Map" class="v53-map"></div><div id="v53MapText" class="muted" style="margin-top:8px"></div><div class="v53-action-row"><button onclick="NUTRI53.layer('risk')">Risk layer</button><button onclick="NUTRI53.layer('coverage')">Coverage layer</button><button onclick="NUTRI53.layer('services')">Services layer</button><button onclick="NUTRI53.layer('markets')">Markets layer</button></div></div></div>
    <div id="v53Alerts" class="v53-tab"><div class="v53-card"><h3>🚨 Early-warning command center</h3><div id="v53AlertList"></div><div class="v53-action-row"><button class="primary" onclick="NUTRI53.generateAlert()">Generate alert bulletin</button><button onclick="NUTRI53.simulateShock()">Simulate shock scenario</button></div></div></div>
    <div id="v53Actions" class="v53-tab"><div class="v53-card"><h3>🎯 Decision & intervention center</h3><div id="v53Decision"></div><div class="v53-action-row"><button class="primary" onclick="NUTRI53.createAction()">Create intervention</button><button onclick="NUTRI53.assign()">Assign response team</button><button onclick="NUTRI53.trackImpact()">Track expected impact</button></div></div></div>
    <div id="v53Audit" class="v53-tab"><div class="v53-card"><h3>🔐 Governance / audit trail</h3><div id="v53AuditLog" class="v53-log"></div><div class="v53-action-row"><button onclick="NUTRI53.audit()">Refresh audit trail</button><button onclick="NUTRI53.share()">Generate secure share link</button></div></div></div>
   </div>`;
   document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d)NUTRI53.close()});
   d.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab,b)));
 }
 function tab(name,btn){['overview','data','gis','alerts','actions','audit'].forEach(x=>{$('v53'+x[0].toUpperCase()+x.slice(1))?.classList.remove('show')});const id='v53'+name[0].toUpperCase()+name.slice(1);$(id)?.classList.add('show');document.querySelectorAll('#v53Shell [data-tab]').forEach(x=>x.classList.toggle('active',x===btn));if(name==='data')renderData();if(name==='gis')renderMap();if(name==='alerts')renderAlerts();if(name==='actions')renderDecision();if(name==='audit')renderAudit();}
 function pipeline(sub){const arr=['Authenticate institutional workspace','Connect authorized source connectors','Resolve country / geography / time context','Validate schema, completeness & provenance','Fuse indicators in NUTRI.N°1 AI engine','Run anomaly + risk scoring','Refresh GIS / dashboards / early warning','Generate decision-ready outputs'];$('v53Pipeline').innerHTML=arr.map((x,i)=>`<div class="v53-step" id="v53p${i}"><i>${i+1}</i><b>${x}</b><span class="v53-status">Queued</span></div>`).join('');arr.forEach((x,i)=>setTimeout(()=>{const e=$('v53p'+i);if(!e)return;e.classList.add('run');e.querySelector('.v53-status').textContent='Processing…'},i*170));arr.forEach((x,i)=>setTimeout(()=>{const e=$('v53p'+i);if(!e)return;e.classList.remove('run');e.classList.add('done');e.querySelector('i').textContent='✓';e.querySelector('.v53-status').textContent='Completed'},650+i*190));}
 function renderCore(){const vs=values(activeSection,activeSubject);const labs=['Coverage','Signal quality','Risk score','Response readiness','Equity','Timeliness','Data completeness'];$('v53Bars').innerHTML=vs.map((v,i)=>`<i class="v53-bar" style="height:6%" title="${labs[i]} ${v}%"></i>`).join('');vs.forEach((v,i)=>setTimeout(()=>{const b=$('v53Bars').children[i];if(b)b.style.height=v+'%'},150+i*80));$('v53Kpis').innerHTML=labs.slice(0,6).map((l,i)=>`<div class="v53-kpi"><small>${l}</small><b>${vs[i]}%</b></div>`).join('');}
 function renderData(){const c=ctx(activeSection);const sources={health:['HMIS / routine health data','NCD + nutrition indicators','Facility / referral signals'],agri:['Production & crop intelligence','Market / price feeds','Climate / satellite signals'],unicef:['Child nutrition surveys','IYCF / maternal indicators','Programme coverage'],who:['NCD risk-factor indicators','Dietary risk signals','Health-system monitoring'],wfp:['Food security indicators','Prices / affordability','Consumption & vulnerability'],fao:['Agrifood production','Post-harvest loss','Food safety / markets'],monitoring:['Project M&E records','Survey rounds','Routine surveillance']}[activeSection]||['Institutional source','Survey source','Analytical source'];$('v53DataTable').innerHTML='<tr><th>Connector</th><th>Status</th><th>Quality</th><th>Last sync</th></tr>'+sources.map((x,i)=>`<tr><td>${x}</td><td>🟢 Connected</td><td>${92-i*3}%</td><td>${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</td></tr>`).join('')+`<tr><td>Context</td><td>${c.country}</td><td>${c.level}</td><td>${c.year}</td></tr>`;}
 function renderMap(layer='risk'){const c=ctx(activeSection),vs=values(activeSection,activeSubject);const pts=[[18,58],[37,35],[55,68],[73,43],[86,72]];$('v53Map').innerHTML=pts.map((p,i)=>`<span class="v53-pin" style="left:${p[0]}%;top:${p[1]}%">${layer} ${i+1}</span>`).join('');$('v53MapText').textContent=`${layer.toUpperCase()} layer • ${c.country} • ${c.level} • ${c.year} • ${vs[2]}% composite signal intensity.`;}
 function renderAlerts(){const vs=values(activeSection,activeSubject);const types=['Price / access anomaly','Nutrition risk signal','Coverage gap','Data quality exception'];$('v53AlertList').innerHTML=types.map((x,i)=>`<div class="v53-alert ${vs[i]>80?'v53-danger':'v53-alert'}"><b>${vs[i]>80?'🔴 High':'🟠 Monitor'} — ${x}</b><div>Signal intensity ${vs[i]}%. Automated triage recommends review and geographic drill-down.</div></div>`).join('');}
 function renderDecision(){const vs=values(activeSection,activeSubject),c=ctx(activeSection);$('v53Decision').innerHTML=`<div class="v53-kpis"><div class="v53-kpi"><small>Priority score</small><b>${vs[2]}/100</b></div><div class="v53-kpi"><small>Response readiness</small><b>${vs[3]}%</b></div><div class="v53-kpi"><small>Expected reach</small><b>${vs[0]}%</b></div></div><div class="v53-alert v53-good"><b>Recommended next action</b><p>Prioritize the highest-signal ${activeSubject.toLowerCase()} hotspot in ${c.country}, validate locally, assign an intervention owner and track outcome indicators through the M&E layer.</p></div>`;}
 function renderAudit(){const now=new Date().toLocaleTimeString();$('v53AuditLog').textContent=`[${now}] workspace authenticated\n[${now}] context resolved: ${ctx(activeSection).country} / ${ctx(activeSection).level} / ${ctx(activeSection).year}\n[${now}] source provenance verified\n[${now}] AI inference run: ${activeSubject}\n[${now}] GIS layer refreshed\n[${now}] early-warning rules evaluated\n[${now}] decision output generated\n[${now}] demonstration mode — no external system modified`}
 function open(sec,sub){ensure();activeSection=sec;activeSubject=sub||NAMES[sec];seq++;$('v53Title').textContent='⚡ '+NAMES[sec]+' — '+activeSubject;$('v53Context').textContent=`LIVE SIMULATION • ${ctx(sec).country} • ${ctx(sec).level} • ${ctx(sec).year} • Run #${seq}`;pipeline(activeSubject);renderCore();renderData();renderMap();renderAlerts();renderDecision();renderAudit();$('v53Result').innerHTML=`<b>Initializing live institutional workflow…</b><p>Orchestrating data, AI, GIS, early warning and decision layers.</p>`;$('v53Shell').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>{$('v53Result').className='v53-alert v53-good';$('v53Result').innerHTML=`<b>✓ End-to-end simulation completed</b><p>${activeSubject} is operationally ready for demonstration: data ingestion, quality gates, AI scoring, geographic intelligence, alerting, intervention logic and M&E traceability have completed successfully.</p><span class="v53-chip">Source sync ✓</span><span class="v53-chip">AI fusion ✓</span><span class="v53-chip">GIS ✓</span><span class="v53-chip">Early warning ✓</span><span class="v53-chip">M&E trace ✓</span>`},2350);}
 window.NUTRI53={open,close:()=>{$('v53Shell')?.classList.remove('show');clearTimeout(timer)},rerun:()=>open(activeSection,activeSubject),drill:()=>{tab('data',document.querySelector('#v53Shell [data-tab="data"]'));toast('Analytical drill-down opened')},export:()=>toast('Executive intelligence brief generated — demonstration export ready'),sync:()=>{toast('Source connectors synchronized');renderData()},validate:()=>{toast('Quality gate passed: provenance + completeness + consistency');renderData()},provenance:()=>{tab('audit',document.querySelector('#v53Shell [data-tab="audit"]'));toast('Provenance chain opened')},layer:x=>{tab('gis',document.querySelector('#v53Shell [data-tab="gis"]'));renderMap(x);toast(x+' layer activated')},generateAlert:()=>{renderAlerts();toast('Early-warning bulletin generated')},simulateShock:()=>{renderAlerts();$('v53Result').className='v53-alert v53-danger';$('v53Result').innerHTML='<b>⚠ Scenario simulation active</b><p>Shock scenario propagated through the selected food / nutrition / health system. Exposure, vulnerability and response priorities recalculated.</p>';toast('Shock scenario propagated through intelligence layers')},createAction:()=>toast('Intervention package created and linked to M&E workspace'),assign:()=>toast('Response team assignment simulated successfully'),trackImpact:()=>toast('Impact pathway activated: baseline → output → outcome → impact'),audit:()=>renderAudit(),share:()=>toast('Secure investor-demo share package generated')};
 function install(){SECTIONS.forEach(sec=>{const r=$(sec);if(!r)return;r.querySelectorAll('.card,.inst-kpi,.ncd-card,.age-card,.risk-row,.alert-row,.feeding-row,.maternal-row,.core-card,.rank,.wizard .step,table tr').forEach(el=>{if(el.closest('#v53Shell'))return;if(el.querySelector('th'))return;el.classList.add('v53-actionable')});let h=r.querySelector('.hero');if(h&&!h.querySelector('.v53-launch')){const b=document.createElement('button');b.className='btn primary v53-launch';b.textContent='⚡ Open Operational Simulation';b.onclick=()=>open(sec,'Full '+NAMES[sec]+' intelligence cycle');h.appendChild(b)}})}
 document.addEventListener('click',e=>{const r=rootOf(e.target);if(!r||e.target.closest('#v53Shell'))return;const btn=e.target.closest('button');if(btn){const oc=btn.getAttribute('onclick')||'';if(/^go\(/.test(oc)||btn.closest('.nav')||btn.classList.contains('sidebar-institution'))return;if(btn.closest('.institution-filters'))return;open(r.id,subject(btn,r.id));return}const el=e.target.closest('.v53-actionable');if(el)open(r.id,subject(el,r.id));});
 document.addEventListener('change',e=>{const r=rootOf(e.target);if(!r)return;const id=e.target.id||'';if(/Country|Level|Year/.test(id)){setTimeout(()=>open(r.id,'Context recalculation — '+clean(e.target.selectedOptions?.[0])||id),180)}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')NUTRI53.close()});
 document.addEventListener('DOMContentLoaded',()=>setTimeout(install,700));
 new MutationObserver(()=>{clearTimeout(window.__v53i);window.__v53i=setTimeout(install,300)}).observe(document.body,{childList:true,subtree:true});
})();
</script>
'''
s=s.replace('</body>',js+'</body>',1)
p.write_text(s,encoding='utf-8')
